[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_zod = { path = "../serde-zod", version = "0.0.0" }
serde = { version = "1.0.139" }
